services:
  - type: web
    name: workoutbrothers-api
    env: node
    buildCommand: npm install
    startCommand: node backend/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DOMAIN
        value: baneworkout.com
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: STRIPE_PUBLIC_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: OPENAI_API_KEY
        sync: false
